version: "3.6"
services:
  postgres:
    image: postgres:16
    ports:
      - ${PGPORT:-5432}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.d-postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: psql -d postgres -U postgres -c 'select * from account limit 1' || exit 1
  graphql-java:
    build: .
    ports:
      - ${SBPORT:-8080}:8080
    environment:
      PGDATABASE: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      SBPORT: 8080
    depends_on:
       postgres:
         condition: service_healthy
