version: "3.6"
services:
  postgres:
    image: postgres:16
    ports:
      - ${PGPORT:-5432}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.d-postgres:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: psql -d postgres -U postgres -c 'select * from account limit 1' || exit 1
  graphql-java:
    build: .
    ports:
      - ${SBPORT:-8080}:8080
    environment:
      PGDATABASE: postgres
      PGHOST: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      SBPORT: 8080
    depends_on:
       postgres:
         condition: service_healthy
  hasura:
    image: hasura/graphql-engine:v2.40.0.cli-migrations-v3
    ports:
      - ${HGEPORT:-8081}:8080
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    volumes:
      - ./metadata:/hasura-metadata:ro
    depends_on:
      postgres:
        condition: service_healthy
  postgraphile:
    image: graphile/postgraphile:4.14.0
    ports:
      - ${GRAPHILEPORT:-5000}:5000
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
