version: 3
endpoint: https://cool-collie-94.hasura.app
admin_secret: XwmRuySEJU7USoSSOF7Awta2ofyj8PqclqBm1ajyQSeenDkuE4ht6UxJXzABnxiY
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
