sources:
  - name: catalog
    handler:
      graphql:
        endpoint: http://localhost:8081/v1/graphql
  - name: fulfillment
    handler:
      graphql:
        endpoint: http://localhost:8082/v1/graphql

additionalTypeDefs: |
  extend type order_detail {
    product: product @resolveTo(
      sourceName: "catalog",
      sourceTypeName: "query_root",
      sourceFieldName: "product_by_pk",
      requiredSelectionSet: "{ id }",
      sourceArgs: {
        id: "{root.order_id}"
      }
    )
  }
