federation_version: =2.0.0
subgraphs:
  catalog:
    routing_url: http://localhost:8081/v1/graphql
    schema:
      subgraph_url: http://localhost:8081/v1/graphql
  fulfillment:
    routing_url: http://localhost:8082/v1/graphql
    schema:
      subgraph_url: http://localhost:8082/v1/graphql
